// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYrbLbXz048pWkXAj9D9UF46bJFcaDnMI',
    appId: '1:226436562911:web:fcab49c24ac3d8338f0e6a',
    messagingSenderId: '226436562911',
    projectId: 'myflutterproject-f0154',
    authDomain: 'myflutterproject-f0154.firebaseapp.com',
    storageBucket: 'myflutterproject-f0154.appspot.com',
    measurementId: 'G-RWDSJQPKQY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDJIHKJfvorX59lWdqDKWZnlH7MM0TshA',
    appId: '1:226436562911:android:042b34ac4fcc38658f0e6a',
    messagingSenderId: '226436562911',
    projectId: 'myflutterproject-f0154',
    storageBucket: 'myflutterproject-f0154.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkg3KJAmhLVXBTtVGUDlHGcwC7P9fXqTk',
    appId: '1:226436562911:ios:fd29c3cde6f281188f0e6a',
    messagingSenderId: '226436562911',
    projectId: 'myflutterproject-f0154',
    storageBucket: 'myflutterproject-f0154.appspot.com',
    iosBundleId: 'com.example.myFlutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkg3KJAmhLVXBTtVGUDlHGcwC7P9fXqTk',
    appId: '1:226436562911:ios:547b65d5d99c75098f0e6a',
    messagingSenderId: '226436562911',
    projectId: 'myflutterproject-f0154',
    storageBucket: 'myflutterproject-f0154.appspot.com',
    iosBundleId: 'com.example.myFlutterProject.RunnerTests',
  );
}
